import 'package:teslacar/utils/styles/app_colors.dart';
import 'package:teslacar/models/car.dart';

class CarsData {
  static const List<Car> carModel = [
    Car(
      id: 1,
      price: '300',
      date: '2020',
      title: 'BMW Serie A',
      rate: '4.8',
      image: 'assets/images/cars/bmw-1.png',
      bgImageName: '01-lemon-cheesecake-bg',
      bgColor: AppColors.white,
    ),
    Car(
      id: 2,
      price: '250',
      date: '2020',
      title: 'BMW Serie B',
      rate: '5',
      image: 'assets/images/cars/bmw-2.png',
      bgImageName: '',
      bgColor: AppColors.white,
    ),
    Car(
      id: 3,
      price: '250',
      date: '2020',
      title: 'BMW Serie C',
      rate: '3.9',
      image: 'assets/images/cars/bmw-3.png',
      bgImageName: '',
      bgColor: AppColors.white,
    ),
    Car(
      id: 4,
      price: '250',
      date: '2020',
      title: 'BMW Serie D',
      rate: '4.3',
      image: 'assets/images/cars/bmw-4.png',
      bgImageName: '',
      bgColor: AppColors.white,
    ),
    Car(
      id: 5,
      price: '250',
      date: '2020',
      title: 'BMW Serie E',
      rate: '5',
      image: 'assets/images/cars/bmw-5.png',
      bgImageName: '',
      bgColor: AppColors.white,
    ),
    Car(
      id: 6,
      price: '250',
      date: '2020',
      title: 'BMW Serie F',
      rate: '3.8',
      image: 'assets/images/cars/bmw-6.png',
      bgImageName: '',
      bgColor: AppColors.white,
    ),
    Car(
      id: 7,
      price: '250',
      date: '2020',
      title: 'BMW Serie G',
      rate: '4.6',
      image: 'assets/images/cars/bmw-7.png',
      bgImageName: '',
      bgColor: AppColors.white,
    ),
    Car(
      id: 8,
      price: '250',
      date: '2020',
      title: 'BMW Serie H',
      rate: '3.8',
      image: 'assets/images/cars/bmw-8.png',
      bgImageName: '',
      bgColor: AppColors.white,
    ),
    Car(
      id: 9,
      price: '250',
      date: '2020',
      title: 'BMW Serie I',
      rate: '3.8',
      image: 'assets/images/cars/bmw-9.png',
      bgImageName: '',
      bgColor: AppColors.white,
    ),
    Car(
      id: 10,
      price: '250',
      date: '2020',
      title: 'BMW Serie J',
      rate: '3.8',
      image: 'assets/images/cars/bmw-10.png',
      bgImageName: '',
      bgColor: AppColors.white,
    ),
    Car(
      id: 11,
      price: '250',
      date: '2020',
      title: 'BMW Serie K',
      rate: '3.8',
      image: 'assets/images/cars/bmw-11.png',
      bgImageName: '',
      bgColor: AppColors.white,
    ),
    Car(
      id: 12,
      price: '250',
      date: '2020',
      title: 'BMW Serie L',
      rate: '3.8',
      image: 'assets/images/cars/bmw-12.png',
      bgImageName: '',
      bgColor: AppColors.white,
    ),
    Car(
      id: 13,
      price: '250',
      date: '2020',
      title: 'BMW Serie M',
      rate: '3.8',
      image: 'assets/images/cars/bmw-13.png',
      bgImageName: '',
      bgColor: AppColors.white,
    ),
    Car(
      id: 14,
      price: '250',
      date: '2020',
      title: 'BMW Serie N',
      rate: '4.0',
      image: 'assets/images/cars/bmw-14.png',
      bgImageName: '',
      bgColor: AppColors.white,
    ),
    Car(
      id: 15,
      price: '250',
      date: '2020',
      title: 'BMW Serie V',
      rate: '5',
      image: 'assets/images/cars/bmw-15.png',
      bgImageName: '',
      bgColor: AppColors.white,
    ),
  ];
}
